### ISSUE TITLE
Test cases failed with EI 6.2.0

### ISSUE THREAD

**Issue by JananiKugaa** [wso2-extensions/esb-connector-pcml#16]
**Description:**
Failed tests:   **callAdditionProgramTestCase**(org.wso2.carbon.connector.pcml.test.integration.AS400PCMLIntegrationTest): Output value does not match. expected:<<xpcml version="6.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='xpcml.xsd'><program name="Addition" path="/QSYS.LIB/%LIBL%.LIB/ADDITION.PGM"><parameterList><intParm name="inputValue1" passDirection="in">5</intParm><intParm name="inputValue2" passDirection="in">10</intParm><intParm name="outputValue" passDirection="out">15<intParm></parameterList></program></xpcml>> but was:<<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="wso2.connector.pcml" xmlns:p="http://services.samples">(..)

**Comment by anupama-pathirage** [comment]
Closing this as this is an old issue and is with MI
